version: "2"

services:

  mongod:
    image: mongo:latest
    volumes:
      - ./mongo/data/db:/data/db
    command: mongod --dbpath /data/db
    hostname: mongod
    ports:
      - 27017:27017
    expose:
      - "27017"

  nodeosd:
    image: eosio/eos:v1.2.0
    volumes:
      - ./eosio/bin/data-dir:/opt/eosio/bin/data-dir
    command: |
      bash -c '
      sleep 8;
      /opt/eosio/bin/nodeosd.sh --filter-on "*" --verbose-http-errors --max-transaction-time=1000 --data-dir /opt/eosio/bin/data-dir -e --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 --plugin eosio::mongo_db_plugin --mongodb-uri=mongodb://mongod:27017/eos --http-validate-host=false;'
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"  
    links:
      - mongod
    depends_on:
      - mongod

  keosd:
    image: eosio/eos:v1.2.0
    volumes:
      - ./eosio/bin/data-dir-wallet:/opt/eosio/bin/data-dir
    command: |
      bash -c '
      sleep 16;
      /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=keosd:8900 --http-alias=localhost:8900;'
    hostname: keosd
    ports:
      - 8900:8900
    links:
      - nodeosd


